StadtPos%[0,0] = 285
StadtPos%[0,1] = 105
StadtPos%[1,0] = 283
StadtPos%[1,1] = 80
StadtPos%[2,0] = 251
StadtPos%[2,1] = 80
StadtPos%[3,0] = 250
StadtPos%[3,1] = 112
StadtPos%[4,0] = 297
StadtPos%[4,1] = 52
StadtPos%[5,0] = 308
StadtPos%[5,1] = 114
StadtPos%[6,0] = 295
StadtPos%[6,1] = 135
StadtPos%[7,0] = 353
StadtPos%[7,1] = 155
StadtPos%[8,0] = 271
StadtPos%[8,1] = 194
StadtPos%[9,0] = 366
StadtPos%[9,1] = 265
StadtPos%[10,0] = 302
StadtPos%[10,1] = 291
StadtPos%[11,0] = 472
StadtPos%[11,1] = 151
StadtPos%[12,0] = 507
StadtPos%[12,1] = 204
StadtPos%[13,0] = 547
StadtPos%[13,1] = 137
StadtPos%[14,0] = 597
StadtPos%[14,1] = 120
StadtPos%[15,0] = 24
StadtPos%[15,1] = 53
StadtPos%[16,0] = 50
StadtPos%[16,1] = 136
StadtPos%[17,0] = 33
StadtPos%[17,1] = 161
StadtPos%[18,0] = 43
StadtPos%[18,1] = 177
StadtPos%[19,0] = 120
StadtPos%[19,1] = 212
StadtPos%[20,0] = 118
StadtPos%[20,1] = 290
StadtPos%[21,0] = 84
StadtPos%[21,1] = 328

Stadtname$[0] = "Rom"
Stadtname$[1] = "Hamburg"
Stadtname$[2] = "London"
Stadtname$[3] = "Madrit"
Stadtname$[4] = "Stockholm"
Stadtname$[5] = "Athen"
Stadtname$[6] = "Kairo"
Stadtname$[7] = "Djidda"
Stadtname$[8] = "Douala"
Stadtname$[9] = "Toamasina"
Stadtname$[10] = "Kapstadt"
Stadtname$[11] = "Kalkutta"
Stadtname$[12] = "Singapur"
Stadtname$[13] = "Shanghai"
Stadtname$[14] = "Tokyo"
Stadtname$[15] = "Eskimo Point"
Stadtname$[16] = "Cherokee Indianerlager"
Stadtname$[17] = "Azteken Stadt"
Stadtname$[18] = "Arwak Indianerlager"
Stadtname$[19] = "Tupi Indianerlager"
Stadtname$[20] = "Iroquois Indianerlager"
Stadtname$[21] = "Palenea"


Stadtbild$[0] = "Rom.bg"
Stadtbild$[1] = "Hamburg.bg"
Stadtbild$[2] = "London.bg"
Stadtbild$[3] = "Madrit.bg"
Stadtbild$[4] = "Stockholm.bg"
Stadtbild$[5] = "Athen.bg"
Stadtbild$[6] = "Kairo.bg"
Stadtbild$[7] = "Djidda.bg"
Stadtbild$[8] = "Douala.bg"
Stadtbild$[9] = "Toamasin.bg"
Stadtbild$[10] = "Kapstadt.bg"
Stadtbild$[11] = "Kalkutta.bg"
Stadtbild$[12] = "Singapur.bg"
Stadtbild$[13] = "Shanghai.bg"
Stadtbild$[14] = "Tokyo.bg"
Stadtbild$[15] = "Eskimo_P.bg"
Stadtbild$[16] = "Cherokee.bg"
Stadtbild$[17] = "Azteken.bg"
Stadtbild$[18] = "Arwak_In.bg"
Stadtbild$[19] = "Tupi_Ind.bg"
Stadtbild$[20] = "Iroquois.bg"
Stadtbild$[21] = "Palenea.bg"



Citty$[0,1] = "Pfeffer, Gold, Mamor, Tee"
Citty$[0,2] = "Skulpturen"

Citty$[1,1] = "Pfeffer, Gold, viel Eisenerz, Öle"
Citty$[1,2] = "viel Stahl, viel Salz"

Citty$[2,1] = "Baumwolle, viel Gold"
Citty$[2,2] = "Schmuck, Kleidung"

Citty$[3,1] = "viel Pfeffer, Stahl, Fisch"
Citty$[3,2] = "Musketen, Werkzeuge"

Citty$[4,1] = "Salz, Stahl"
Citty$[4,2] = "Werkzeuge, Musketen, viel Holz"

Citty$[5,1] = "Pfeffer, Salz, viel Gold, viel Kakao"
Citty$[5,2] = "viel Schmuck"

Citty$[6,1] = "Musketen, Holz"
Citty$[6,2] = "Salz, viel Öle"

Citty$[7,1] = "Kanonen"
Citty$[7,2] = ""

Citty$[8,1] = "Wergzeuge, Kakao"
Citty$[8,2] = "Elfenbein, viel Diamanten"

Citty$[9,1] = "Musketen"
Citty$[9,2] = "Elfenbein,viel Gold"

Citty$[10,1] = "Kanonen"
Citty$[10,2] = "viel Elfenbein, Diamanten"

Citty$[11,1] = "Öle, viel Baumwolle"
Citty$[11,2] = "viel Kleidung, "

Citty$[12,1] = "viel Gold, Kanonen"
Citty$[12,2] = "viel Tee, Eisenerz"

Citty$[13,1] = "Stahl, Salz, Öle"
Citty$[13,2] = "Werkzeuge, Kanonen"

Citty$[14,1] = 8
Citty$[14,2] = 8

Citty$[15,1] = 5,14
Citty$[15,2] = 13,2

Citty$[16,1] = 3,4
Citty$[16,2] = 0,9

Citty$[17,1] = 3,4,12
Citty$[17,2] = 9,11

Citty$[18,1] = 10,7
Citty$[18,2] = 8,9

Citty$[19,1] = 4,5
Citty$[19,2] = 0,6

Citty$[20,1] = 1,2,3
Citty$[20,2] = 6

Citty$[21,1] = 0
Citty$[21,2] = 8,7

Produkt$[0]="Nahrung"
Produkt$[1]="Skulpturen"
Produkt$[2]="Kleidung"
Produkt$[3]="Schmuck"
Produkt$[4]="Musketen"
Produkt$[5]="Werkzeuge"
Produkt$[6]="Eisenerz"
Produkt$[7]="Diamanten"
Produkt$[8]="Kakao"
Produkt$[9]="Baumwolle"
Produkt$[10]="Elfenbein"
Produkt$[11]="Medikamente"
Produkt$[12]="Salz"
Produkt$[13]="Fisch"
Produkt$[14]="Holz"
Produkt$[15]=""
Produkt$[16]=""
Produkt$[17]=""
Produkt$[18]=""
Produkt$[19]=""
Produkt$[20]=""
